import { MarketplaceConfig, MarketplaceId, ContentType } from '../types';

export const MARKETPLACE_CONFIGS: Record<MarketplaceId, MarketplaceConfig> = {
  'adobe-stock': {
    id: 'adobe-stock',
    name: 'Adobe Stock',
    badgeColor: 'bg-red-50 text-red-700 border-red-200',
    minTitleLength: 15,
    maxTitleLength: 200,
    minKeywords: 5,
    maxKeywords: 49,
    recommendedKeywordsCount: [25, 45],
    supportsCategories: true,
    categories: [
      'Animals',
      'Buildings and Architecture',
      'Business',
      'Drinks',
      'The Environment',
      'States of Mind',
      'Food',
      'Graphic Resources',
      'Hobbies and Leisure',
      'Industry',
      'Landscape',
      'Lifestyle',
      'People',
      'Plants and Flowers',
      'Culture and Religion',
      'Science',
      'Social Issues',
      'Sports',
      'Technology',
      'Transport',
      'Travel'
    ],
    guidelines: [
      'The first 10 keywords are weighted heavily in Adobe search algorithm.',
      'Title should be natural, 5-15 words (ideal 40-70 characters).',
      'Maximum 49 keywords; 25-45 is optimal.',
      'Do not spam camera technical details in keywords unless visually crucial.'
    ]
  },
  'shutterstock': {
    id: 'shutterstock',
    name: 'Shutterstock',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    minTitleLength: 20,
    maxTitleLength: 200,
    minKeywords: 7,
    maxKeywords: 50,
    recommendedKeywordsCount: [25, 48],
    supportsCategories: true,
    categories: [
      'Abstract',
      'Animals/Wildlife',
      'The Arts',
      'Backgrounds/Textures',
      'Beauty/Fashion',
      'Buildings/Landmarks',
      'Business/Finance',
      'Celebrities',
      'Education',
      'Food and Drink',
      'Healthcare/Medical',
      'Holidays',
      'Illustrations/Clip-Art',
      'Industrial',
      'Interiors',
      'Miscellaneous',
      'Nature',
      'Objects',
      'Parks/Outdoor',
      'People',
      'Religion',
      'Science',
      'Signs/Symbols',
      'Sports/Recreation',
      'Technology',
      'Transportation',
      'Vectors',
      'Vintage'
    ],
    guidelines: [
      'Descriptions must be at least 5 words and clearly describe who, what, and where.',
      'Allow up to 50 keywords. Avoid non-English or trademarked terms.',
      'Select 1-2 relevant categories.'
    ]
  },
  'vecteezy': {
    id: 'vecteezy',
    name: 'Vecteezy',
    badgeColor: 'bg-amber-50 text-amber-800 border-amber-200',
    minTitleLength: 15,
    maxTitleLength: 150,
    minKeywords: 5,
    maxKeywords: 50,
    recommendedKeywordsCount: [20, 40],
    supportsCategories: true,
    categories: [
      'Backgrounds',
      'Banners',
      'Business & Finance',
      'Celebrations & Holidays',
      'Education',
      'Food & Drink',
      'Icons & Symbols',
      'Illustrations',
      'Infographics',
      'Nature & Landscapes',
      'Patterns',
      'People',
      'Technology',
      'Transportation',
      'Travel & Tourism',
      'Vectors'
    ],
    guidelines: [
      'Highlight visual styling (e.g. isometric, flat, watercolor, vector).',
      'Keep titles concise and commercial.',
      'Keyword tags must avoid duplicates and plural variants of the same root.'
    ]
  },
  'freepik': {
    id: 'freepik',
    name: 'Freepik',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    minTitleLength: 15,
    maxTitleLength: 120,
    minKeywords: 5,
    maxKeywords: 50,
    recommendedKeywordsCount: [20, 40],
    supportsCategories: true,
    categories: [
      'Vectors',
      'Photos',
      'PSD Mockups',
      'Icons',
      'AI Images',
      'Backgrounds',
      'Banners',
      'Flyers',
      'Cards & Invitations',
      'Business',
      'People',
      'Nature',
      'Food',
      'Technology'
    ],
    guidelines: [
      'Short descriptive titles, usually lowercase or sentence case.',
      'Freepik prioritizes high-intent search queries.',
      'Tag ordering is important; put direct visual subjects first.'
    ]
  },
  'istock': {
    id: 'istock',
    name: 'iStock / Getty Images',
    badgeColor: 'bg-violet-50 text-violet-700 border-violet-200',
    minTitleLength: 15,
    maxTitleLength: 180,
    minKeywords: 5,
    maxKeywords: 50,
    recommendedKeywordsCount: [20, 45],
    supportsCategories: true,
    categories: [
      'Creative Photos',
      'Creative Vector & Illustration',
      'Editorial',
      'Business & Technology',
      'Family & Relationships',
      'Healthcare & Medicine',
      'Nature & Wildlife',
      'Sports & Recreation',
      'Food & Beverage',
      'Travel & Destinations'
    ],
    guidelines: [
      'Getty uses controlled vocabulary; prioritize clean singular conceptual keywords.',
      'Strict separation between Commercial and Editorial content.',
      'Avoid vague descriptors.'
    ]
  },
  'dreamstime': {
    id: 'dreamstime',
    name: 'Dreamstime',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    minTitleLength: 20,
    maxTitleLength: 200,
    minKeywords: 5,
    maxKeywords: 50,
    recommendedKeywordsCount: [25, 45],
    supportsCategories: true,
    categories: [
      'Abstract & Backgrounds',
      'Animals',
      'Architecture',
      'Business',
      'Editorial',
      'Holidays & Events',
      'IT & Computer',
      'Illustrations & Cliparts',
      'Nature',
      'People',
      'Objects',
      'Technology',
      'Travel'
    ],
    guidelines: [
      'Dreamstime requires both Title and Description (min 5 words each).',
      'Keyword stuffing will trigger rejection.',
      'Category selection is mandatory.'
    ]
  },
  'generic': {
    id: 'generic',
    name: 'Generic Stock Metadata',
    badgeColor: 'bg-slate-100 text-slate-700 border-slate-200',
    minTitleLength: 15,
    maxTitleLength: 200,
    minKeywords: 5,
    maxKeywords: 50,
    recommendedKeywordsCount: [25, 45],
    supportsCategories: true,
    categories: [
      'Nature & Landscapes',
      'People & Lifestyle',
      'Business & Work',
      'Technology & Science',
      'Food & Dining',
      'Architecture & City',
      'Travel & Tourism',
      'Abstract & Texture',
      'Health & Wellness',
      'Animals & Pets',
      'Education',
      'Arts & Entertainment'
    ],
    guidelines: [
      'Universally compliant IPTC / XMP metadata format.',
      'Compatible with Adobe Bridge, ExifTool, and all microstock uploaders.',
      'Standard comma-separated keywords and descriptive titles.'
    ]
  }
};
